# 欢迎使用 Jekyll！
#
# 这个配置文件是用于设置影响整个网站的参数，
# 一般是只需要设置一次，并很少需要再修改的内容。
# 出于技术原因，当使用 `jekyll serve -l -H localhost` 时，
# 如果更改了这个文件，需要重启服务器进程才能生效。

# 网站基本设置
locale                   : "en-US"    # 语言区域设置为美式英语
title                    : "Daqian Shi"    # 网站的标题
title_separator          : "-"    # 标题分隔符
name                     : &name "Daqian Shi"    # 网站的名称，定义为一个锚点(&name)以便重用
description              : &description "Daqian Info"    # 网站的描述，定义为锚点(&description)以便在其他地方重用
url                      : https://daqians.github.io    # 网站的基本地址，例如 "https://example.com"
baseurl                  : ""    # 网站的子路径，如果网站不在根目录，例如 "/blog"
repository               : "daqians/daqians.github.io"    # 项目所在的代码仓库地址

# 网站作者信息 - 控制侧边栏作者内容的设置。
# 如果某一字段为空，则该图标和链接将不出现，否则会展示出来。
# 可以通过编辑 /_includes/author-profile.html 文件进一步定制化。
author:
  # 作者简介信息
  avatar           : "sdq.png"    # 作者头像图片路径
  name             : "Dr. Daqian Shi"    # 作者姓名
  pronouns         :    # 代词（例如："she/her"），如果需要显示性别偏好，可填写该字段
  bio              : "Short biography for the left-hand sidebar"    # 简短的个人介绍，显示在左侧边栏
  location         : "Earth"    # 作者位置
  employer         : "Red Brick University"    # 作者的工作单位名称
  uri              :    # 个人网站地址（留空则不显示）
  email            : "none@example.org"    # 电子邮件地址

  # 学术网站链接
  arxiv            :    # arXiv 个人主页 URL
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"    # Google Scholar 个人主页
  impactstory      :    # ImpactStory 个人主页 URL
  orcid            : "http://orcid.org/yourorcidurl"    # ORCID 个人主页 URL
  semantic         :    # Semantic Scholar 个人主页 URL
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"    # PubMed 搜索 URL
  researchgate     :    # ResearchGate 个人主页 URL
  scopus           :    # Scopus 个人主页 URL

  # 代码仓库和软件开发相关的链接
  bitbucket        :    # Bitbucket 用户名
  codepen          :    # CodePen 用户名
  dribbble         :    # Dribbble 用户名
  github           : "academicpages"    # GitHub 用户名
  kaggle           :    # Kaggle 用户名
  stackoverflow    :    # Stack Overflow 用户编号或编号和名称（例如 "1" 或 "1/jeff-atwood"）

  # 社交媒体链接
  bluesky          : "bsky.app"    # Bluesky 社交平台的用户名
  facebook         :    # Facebook 用户名
  flickr           :    # Flickr 用户名
  foursquare       :    # Foursquare 用户名
  goodreads        :    # Goodreads 用户名
  google_plus      :    # Google Plus 用户名
  keybase          :    # Keybase 用户名
  instagram        :    # Instagram 用户名
  lastfm           :    # Last.fm 用户名
  linkedin         :    # LinkedIn 用户名
  mastodon         :    # Mastodon URL
  medium           :    # Medium URL
  pinterest        :    # Pinterest 用户名
  soundcloud       :    # SoundCloud 用户名
  steam            :    # Steam 用户名
  telegram         :    # Telegram URL
  tumblr           :    # Tumblr 用户名
  twitter          :    # Twitter（现 X）用户名
  vine             :    # Vine 用户名
  weibo            :    # 微博用户名
  wikipedia        :    # 维基百科用户名
  xing             :    # Xing 用户名
  youtube          :    # YouTube 用户名
  zhihu            :    # 知乎用户名

# 发表类别 - 定义发表内容的类别及其标题
publication_category:
  books:
    title: 'Books'    # 书籍类的标题
  manuscripts:
    title: 'Journal Articles'    # 期刊文章的标题
  conferences:
    title: 'Conference Papers'    # 会议论文的标题

# 网站其他设置
teaser                   :    # 预览图片的文件名，放在 /images/ 中，例如 "500x300.png"
breadcrumbs              : false    # 是否显示面包屑导航（true 或 false），默认是 false
words_per_minute         : 160    # 每分钟阅读的单词数，影响阅读时间的计算
future                   : true    # 是否显示未来日期发布的文章
read_more                : "disabled"    # 是否启用 "阅读更多" 链接
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               :    # 评论服务提供商，例如 "disqus"， "discourse"， "facebook" 等，默认是 false
  disqus:
    shortname            :
  discourse:
    server               :    # Discourse 评论服务器地址
  facebook:
    appid                :
    num_posts            :    # 显示的评论数量，默认为 5
    colorscheme          :    # "light" 或 "dark" 配色方案
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']    # Staticman 允许的字段列表
  branch                 : "gh-pages"    # 分支名称（例如： "master", "gh-pages"）
  commitMessage          : "New comment."    # 提交评论的消息内容
  filename               : comment-{@timestamp}    # 评论文件的命名方式
  format                 : "yml"    # 评论文件的格式（例如 "yml"）
  moderation             : true    # 是否启用评论审核
  path                   : "_data/comments/{options.slug}"    # 评论存储路径
  requiredFields         : ['name', 'email', 'message']    # 必填字段列表
  transforms:
    email                : "md5"    # 对 email 字段进行 md5 加密
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"    # 日期格式 "iso8601"，可选 "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # 是否隐藏 RSS 链接
  path                   : # blank (default) uses feed.xml


# SEO 相关设置
google_site_verification :    # Google 网站验证代码
bing_site_verification   :    # Bing 网站验证代码
alexa_site_verification  :    # Alexa 网站验证代码
yandex_site_verification :    # Yandex 网站验证代码

# 社交分享设置
twitter:
  username               : &twitter    # Twitter 用户名
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :    # Open Graph/Twitter 默认的站点图片
# 指定社交媒体个人资料的链接
social:
  type                   :    # 个人或组织，默认为个人
  name                   :    # 如果用户名与站点名称不同，可以在此指定
  links:    # 一个包含社交媒体个人资料链接的数组

# 分析工具集成
analytics:
  provider               :  "false"    # 分析服务提供商（例如 "google" 或 "google-analytics-4"），默认关闭
  google:
    tracking_id          :    # Google 分析跟踪 ID

# 文件读取设置
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"    # 允许的 Markdown 文件扩展名

# 转换设置
markdown: kramdown    # 使用 kramdown 作为 Markdown 解析器
highlighter: rouge    # 使用 rouge 作为代码高亮器
lsi: false    # 是否启用潜在语义索引（LSI）
excerpt_separator: "\n\n"    # 文章摘要的分隔符
incremental: false    # 增量生成开关

# Markdown 处理设置
kramdown:
  input: GFM    # 使用 GitHub 风格的 Markdown (GFM)
  hard_wrap: false    # 是否启用硬换行
  auto_ids: true    # 自动为标题生成 ID
  footnote_nr: 1    # 脚注起始编号
  entity_output: as_char    # 实体输出设置为字符
  toc_levels: 1..6    # 目录级别设置为 1 到 6
  smart_quotes: lsquo,rsquo,ldquo,rdquo    # 智能引号样式设置
  enable_coderay: false    # 禁用 CodeRay 代码高亮

# 集合设置 - 控制网站的各种内容集合
collections:
  teaching:
    output: true
    permalink: /:collection/:path/    # 设置集合的输出和链接格式
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# 页面和集合的默认设置
defaults:
  # _posts 集合的默认设置
  - scope:
      path: ""
      type: posts
    values:
      layout: single    # 使用单一布局
      author_profile: true    # 启用作者简介
      read_time: true    # 显示阅读时间
      comments: true    # 启用评论
      share: true    # 启用社交分享
      related: true    # 启用相关文章
  # _pages 集合的默认设置
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching 集合的默认设置
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications 集合的默认设置
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio 集合的默认设置
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks 集合的默认设置
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS 设置
sass:
  sass_dir: _sass    # Sass 文件目录
  style: compressed    # Sass 文件的输出风格，设置为压缩格式

# 输出设置
permalink: /:categories/:title/    # 设置文章永久链接的格式
# paginate: 5    # 分页，每页显示 5 篇文章
# paginate_path: /page:num/
timezone: Etc/UTC    # 设置时区为 UTC

# 插件设置
plugins:
  - jekyll-feed    # RSS feed 插件
  - jekyll-gist    # 集成 GitHub Gist 的插件
  - jekyll-paginate    # 分页插件
  - jekyll-sitemap    # 生成网站地图的插件
  - jemoji    # 集成 emoji 表情的插件

# 模拟 GitHub Pages 环境的 --safe 参数
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# 归档设置
#   类型
#   - 使用 Liquid 模板生成的归档页面，类型为 "liquid"（默认）
#   - 使用 Jekyll Archives 插件生成归档页面，类型为 "jekyll-archives"
#   路径 (示例)
#   - 当使用 Liquid 方法时，归档页面应存在于指定路径，否则可能会出现链接断开的情况
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/

# HTML 压缩设置
# - 参考：http://jch.penibelst.de/
compress_html:
  clippings: all    # 压缩所有的 HTML 剪切
  ignore:
    envs: development    # 在开发环境中忽略 HTML 压缩
